title: "Yuvanshâ€™s Lab"
description: "Things I learn, build and explore."
baseurl: ""
url: "https://yuvansh.info"

markdown: kramdown
theme: null

permalink: /:categories/:year/:month/:day/:title/

collections:
  gallery:
    output: true
    permalink: /gallery/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "gallery_item"

social:
  linkedin: "https://www.linkedin.com/in/your-yuvansh-link-here"
  youtube: "https://www.youtube.com/@your-channel-or-placeholder"
  github: "https://github.com/your-yuvansh-handle"
  email: "hello@yuvansh.info"

